import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

const cweTop25 = {
  version: '2023',
  description: 'CWE Top 25 Most Dangerous Software Weaknesses',
  weaknesses: [
    {
      rank: 1,
      id: 'CWE-787',
      name: 'Out-of-bounds Write',
      description: 'The software writes data past the end, or before the beginning, of the intended buffer.',
      languages: ['C', 'C++'],
      consequences: ['Code Execution', 'DoS', 'Data Corruption'],
    },
    {
      rank: 2,
      id: 'CWE-79',
      name: 'Improper Neutralization of Input During Web Page Generation (XSS)',
      description: 'The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page.',
      languages: ['JavaScript', 'PHP', 'Python', 'Java'],
      consequences: ['Session Hijacking', 'Data Theft', 'Defacement'],
    },
    {
      rank: 3,
      id: 'CWE-89',
      name: 'Improper Neutralization of Special Elements used in an SQL Command (SQL Injection)',
      description: 'The software constructs all or part of an SQL command using externally-influenced input without proper neutralization.',
      languages: ['All'],
      consequences: ['Data Breach', 'Data Manipulation', 'Authentication Bypass'],
    },
    {
      rank: 4,
      id: 'CWE-416',
      name: 'Use After Free',
      description: 'Referencing memory after it has been freed can cause a program to crash, use unexpected values, or execute code.',
      languages: ['C', 'C++'],
      consequences: ['Code Execution', 'DoS'],
    },
    {
      rank: 5,
      id: 'CWE-78',
      name: 'Improper Neutralization of Special Elements used in an OS Command (OS Command Injection)',
      description: 'The software constructs all or part of an OS command using externally-influenced input without proper neutralization.',
      languages: ['All'],
      consequences: ['Code Execution', 'System Compromise'],
    },
    {
      rank: 6,
      id: 'CWE-20',
      name: 'Improper Input Validation',
      description: 'The product receives input but does not validate or incorrectly validates that the input has the properties required for safe processing.',
      languages: ['All'],
      consequences: ['Various - depends on context'],
    },
    {
      rank: 7,
      id: 'CWE-125',
      name: 'Out-of-bounds Read',
      description: 'The software reads data past the end, or before the beginning, of the intended buffer.',
      languages: ['C', 'C++'],
      consequences: ['Information Disclosure', 'DoS'],
    },
    {
      rank: 8,
      id: 'CWE-22',
      name: 'Improper Limitation of a Pathname to a Restricted Directory (Path Traversal)',
      description: 'The software uses external input to construct a pathname without properly neutralizing special elements.',
      languages: ['All'],
      consequences: ['Information Disclosure', 'File Manipulation'],
    },
    {
      rank: 9,
      id: 'CWE-352',
      name: 'Cross-Site Request Forgery (CSRF)',
      description: 'The web application does not sufficiently verify that a request was intentionally submitted by the authenticated user.',
      languages: ['Web Applications'],
      consequences: ['Unauthorized Actions', 'State Changes'],
    },
    {
      rank: 10,
      id: 'CWE-434',
      name: 'Unrestricted Upload of File with Dangerous Type',
      description: 'The software allows the attacker to upload files of dangerous types that can be processed within the environment.',
      languages: ['Web Applications'],
      consequences: ['Code Execution', 'System Compromise'],
    },
    {
      rank: 11,
      id: 'CWE-862',
      name: 'Missing Authorization',
      description: 'The software does not perform authorization checks when an actor attempts to access a resource or perform an action.',
      languages: ['All'],
      consequences: ['Unauthorized Access', 'Privilege Escalation'],
    },
    {
      rank: 12,
      id: 'CWE-476',
      name: 'NULL Pointer Dereference',
      description: 'A NULL pointer dereference occurs when the application dereferences a pointer that it expects to be valid, but is NULL.',
      languages: ['C', 'C++'],
      consequences: ['DoS', 'Code Execution'],
    },
    {
      rank: 13,
      id: 'CWE-287',
      name: 'Improper Authentication',
      description: 'The software does not properly verify that the claimed identity is actually the one claimed.',
      languages: ['All'],
      consequences: ['Authentication Bypass', 'Impersonation'],
    },
    {
      rank: 14,
      id: 'CWE-190',
      name: 'Integer Overflow or Wraparound',
      description: 'The software performs a calculation that can produce an integer overflow or wraparound.',
      languages: ['C', 'C++', 'Java'],
      consequences: ['DoS', 'Code Execution', 'Logic Errors'],
    },
    {
      rank: 15,
      id: 'CWE-502',
      name: 'Deserialization of Untrusted Data',
      description: 'The application deserializes untrusted data without sufficiently verifying that the resulting data will be valid.',
      languages: ['Java', 'Python', 'PHP', '.NET'],
      consequences: ['Code Execution', 'System Compromise'],
    },
    {
      rank: 16,
      id: 'CWE-77',
      name: 'Improper Neutralization of Special Elements used in a Command (Command Injection)',
      description: 'The software constructs all or part of a command using externally-influenced input without proper neutralization.',
      languages: ['All'],
      consequences: ['Code Execution', 'System Compromise'],
    },
    {
      rank: 17,
      id: 'CWE-119',
      name: 'Improper Restriction of Operations within the Bounds of a Memory Buffer',
      description: 'The software performs operations on a memory buffer without properly validating buffer boundaries.',
      languages: ['C', 'C++'],
      consequences: ['Code Execution', 'DoS', 'Information Disclosure'],
    },
    {
      rank: 18,
      id: 'CWE-798',
      name: 'Use of Hard-coded Credentials',
      description: 'The software contains hard-coded credentials for inbound or outbound authentication.',
      languages: ['All'],
      consequences: ['Authentication Bypass', 'Unauthorized Access'],
    },
    {
      rank: 19,
      id: 'CWE-918',
      name: 'Server-Side Request Forgery (SSRF)',
      description: 'The web server receives a URL from an upstream component and retrieves its contents without sufficient validation.',
      languages: ['Web Applications'],
      consequences: ['Internal Network Access', 'Data Exfiltration'],
    },
    {
      rank: 20,
      id: 'CWE-306',
      name: 'Missing Authentication for Critical Function',
      description: 'The software does not perform authentication for functionality that requires authentication.',
      languages: ['All'],
      consequences: ['Unauthorized Access', 'Data Manipulation'],
    },
    {
      rank: 21,
      id: 'CWE-362',
      name: 'Concurrent Execution using Shared Resource with Improper Synchronization (Race Condition)',
      description: 'The program contains a code sequence that can run concurrently with other code in a way that causes data corruption.',
      languages: ['All'],
      consequences: ['DoS', 'Data Corruption', 'Security Bypass'],
    },
    {
      rank: 22,
      id: 'CWE-269',
      name: 'Improper Privilege Management',
      description: 'The software does not properly assign, modify, track, or check privileges for an actor.',
      languages: ['All'],
      consequences: ['Privilege Escalation', 'Unauthorized Access'],
    },
    {
      rank: 23,
      id: 'CWE-94',
      name: 'Improper Control of Generation of Code (Code Injection)',
      description: 'The software constructs all or part of a code segment using externally-influenced input without proper neutralization.',
      languages: ['JavaScript', 'Python', 'PHP'],
      consequences: ['Code Execution', 'System Compromise'],
    },
    {
      rank: 24,
      id: 'CWE-863',
      name: 'Incorrect Authorization',
      description: 'The software performs authorization checks incorrectly, allowing actors to access resources outside their intended permissions.',
      languages: ['All'],
      consequences: ['Unauthorized Access', 'Data Breach'],
    },
    {
      rank: 25,
      id: 'CWE-276',
      name: 'Incorrect Default Permissions',
      description: 'During installation, the software sets incorrect permissions for an object, exposing it to unintended actors.',
      languages: ['All'],
      consequences: ['Unauthorized Access', 'Information Disclosure'],
    },
  ],
};

export function registerCweReferenceResource(server: McpServer): void {
  server.resource(
    'cwe-top-25',
    'security://cwe-top-25',
    {
      description: 'CWE Top 25 Most Dangerous Software Weaknesses (2023)',
      mimeType: 'application/json',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'application/json',
          text: JSON.stringify(cweTop25, null, 2),
        },
      ],
    })
  );
}
