import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

const owaspTop10 = {
  version: '2021',
  vulnerabilities: [
    {
      id: 'A01:2021',
      name: 'Broken Access Control',
      description: 'Access control enforces policy such that users cannot act outside of their intended permissions. Failures typically lead to unauthorized information disclosure, modification, or destruction of data.',
      examples: [
        'Violation of the principle of least privilege',
        'Bypassing access control checks by modifying the URL',
        'Permitting viewing or editing someone else\'s account',
        'Accessing API with missing access controls for POST, PUT and DELETE',
        'Elevation of privilege (acting as admin when logged in as user)',
        'CORS misconfiguration allowing API access from unauthorized origins',
        'Force browsing to authenticated pages or privileged pages',
      ],
      prevention: [
        'Implement access control mechanisms once and reuse throughout the application',
        'Deny by default, except for public resources',
        'Model access controls should enforce record ownership',
        'Disable web server directory listing',
        'Log access control failures and alert admins',
        'Rate limit API and controller access',
        'Invalidate JWT tokens on logout',
      ],
    },
    {
      id: 'A02:2021',
      name: 'Cryptographic Failures',
      description: 'Previously known as Sensitive Data Exposure. Focuses on failures related to cryptography which often lead to exposure of sensitive data.',
      examples: [
        'Data transmitted in clear text (HTTP, SMTP, FTP)',
        'Old or weak cryptographic algorithms (MD5, SHA1, DES)',
        'Default crypto keys in use or weak keys generated',
        'Encryption not enforced (missing HTTP headers)',
        'Server certificate not validated',
        'Passwords stored using reversible encryption',
        'Deprecated hash functions for password storage',
      ],
      prevention: [
        'Classify data processed, stored, or transmitted',
        'Don\'t store sensitive data unnecessarily',
        'Encrypt all sensitive data at rest',
        'Use up-to-date and strong algorithms and keys',
        'Encrypt data in transit with TLS',
        'Disable caching for sensitive data',
        'Store passwords using strong salted hashing (Argon2, bcrypt)',
      ],
    },
    {
      id: 'A03:2021',
      name: 'Injection',
      description: 'Injection flaws occur when untrusted data is sent to an interpreter as part of a command or query. SQL, NoSQL, OS, and LDAP injection are common.',
      examples: [
        'SQL injection through user input',
        'NoSQL injection in MongoDB queries',
        'OS command injection',
        'LDAP injection',
        'Expression Language injection',
        'ORM injection',
        'XML/XPath injection',
      ],
      prevention: [
        'Use safe APIs with parameterized interfaces',
        'Use positive server-side input validation',
        'Escape special characters for residual dynamic queries',
        'Use LIMIT and other SQL controls to prevent mass disclosure',
        'Use ORMs with parameterized queries',
        'Separate commands from data',
      ],
    },
    {
      id: 'A04:2021',
      name: 'Insecure Design',
      description: 'A new category focusing on risks related to design and architectural flaws. Secure design requires threat modeling, secure design patterns, and reference architectures.',
      examples: [
        'Credential recovery with "security questions"',
        'Missing rate limiting on authentication',
        'Bot protection that can be bypassed',
        'Trust boundaries not defined',
        'Lack of tenant isolation in multi-tenant apps',
        'Business logic flaws',
      ],
      prevention: [
        'Establish secure development lifecycle with AppSec professionals',
        'Use threat modeling for critical authentication and access control',
        'Integrate security language and controls into user stories',
        'Write unit and integration tests to validate critical flows',
        'Segregate tier layers on network level',
        'Limit resource consumption by user or service',
      ],
    },
    {
      id: 'A05:2021',
      name: 'Security Misconfiguration',
      description: 'Missing appropriate security hardening or misconfigured permissions on cloud services. Ad hoc or poor configuration leads to vulnerabilities.',
      examples: [
        'Missing security hardening across application stack',
        'Unnecessary features enabled or installed',
        'Default accounts and passwords unchanged',
        'Error handling reveals stack traces',
        'Upgraded systems with security features disabled',
        'Security settings in frameworks not set to secure values',
        'Missing security headers',
        'Software is out of date or vulnerable',
      ],
      prevention: [
        'Repeatable hardening process with automation',
        'Minimal platform without unnecessary features',
        'Review and update configurations for patches and updates',
        'Segmented application architecture',
        'Send security directives to clients',
        'Automated verification of configurations',
      ],
    },
    {
      id: 'A06:2021',
      name: 'Vulnerable and Outdated Components',
      description: 'Components such as libraries, frameworks, and software modules run with the same privileges as the application. Vulnerable components can undermine application defenses.',
      examples: [
        'Unknown versions of components used',
        'Vulnerable, unsupported, or outdated software',
        'Irregular vulnerability scanning',
        'Lack of timely patching',
        'Incompatible or untested component upgrades',
        'Unsecured component configurations',
      ],
      prevention: [
        'Remove unused dependencies and features',
        'Continuously inventory component versions',
        'Monitor CVE and NVD for vulnerabilities',
        'Obtain components from official sources',
        'Monitor unmaintained libraries',
        'Use software composition analysis tools',
      ],
    },
    {
      id: 'A07:2021',
      name: 'Identification and Authentication Failures',
      description: 'Confirmation of user identity, authentication, and session management is critical. Weak authentication can lead to complete system compromise.',
      examples: [
        'Permits credential stuffing or brute force',
        'Permits default, weak, or well-known passwords',
        'Uses weak credential recovery processes',
        'Uses plain text or weakly hashed passwords',
        'Missing or ineffective MFA',
        'Exposes session identifier in URL',
        'Reuses session identifier after login',
        'Doesn\'t properly invalidate sessions',
      ],
      prevention: [
        'Implement multi-factor authentication',
        'Don\'t ship with default credentials',
        'Implement weak-password checks',
        'Align password policies with NIST guidelines',
        'Harden against credential enumeration attacks',
        'Limit failed login attempts',
        'Use server-side session manager with secure session IDs',
      ],
    },
    {
      id: 'A08:2021',
      name: 'Software and Data Integrity Failures',
      description: 'Code and infrastructure that does not protect against integrity violations. Includes insecure deserialization and using components from untrusted sources.',
      examples: [
        'Using libraries from untrusted CDNs',
        'Auto-update without integrity verification',
        'Insecure CI/CD pipeline',
        'Insecure deserialization of untrusted data',
        'Missing code signing',
        'Unverified serialized objects',
      ],
      prevention: [
        'Use digital signatures to verify software/data',
        'Ensure dependencies are from trusted repositories',
        'Use software supply chain security tools',
        'Implement code review for changes',
        'Ensure CI/CD pipeline has proper segregation and access control',
        'Don\'t send unsigned/unencrypted serialized data to untrusted clients',
      ],
    },
    {
      id: 'A09:2021',
      name: 'Security Logging and Monitoring Failures',
      description: 'Without logging and monitoring, breaches cannot be detected. Insufficient logging, detection, monitoring, and active response occurs at most breach incidents.',
      examples: [
        'Auditable events not logged',
        'Warnings and errors generate no/unclear logs',
        'Logs not monitored for suspicious activity',
        'Logs only stored locally',
        'Alerting thresholds not in place',
        'Penetration testing doesn\'t trigger alerts',
        'Application can\'t detect active attacks in real-time',
      ],
      prevention: [
        'Log all login, access control, and input validation failures',
        'Ensure logs are in consumable format for log management',
        'Encode log data correctly to prevent injection',
        'Ensure high-value transactions have audit trail',
        'Establish effective monitoring and alerting',
        'Establish incident response and recovery plan',
      ],
    },
    {
      id: 'A10:2021',
      name: 'Server-Side Request Forgery (SSRF)',
      description: 'SSRF flaws occur when a web application fetches a remote resource without validating the user-supplied URL. Attackers can coerce the server to make requests to unintended locations.',
      examples: [
        'Fetching URL from user input',
        'Accessing cloud service metadata URLs',
        'Internal port scanning',
        'Accessing internal services behind firewalls',
        'File retrieval via file:// scheme',
        'Using redirects to bypass validation',
      ],
      prevention: [
        'Segment remote resource access functionality',
        'Enforce "deny by default" firewall policies',
        'Sanitize and validate all client-supplied input data',
        'Enforce URL schema, port, and destination with allowlist',
        'Don\'t send raw responses to clients',
        'Disable HTTP redirections',
      ],
    },
  ],
};

export function registerOwaspTop10Resource(server: McpServer): void {
  server.resource(
    'owasp-top-10',
    'security://owasp-top-10',
    {
      description: 'OWASP Top 10 Web Application Security Risks (2021)',
      mimeType: 'application/json',
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.href,
          mimeType: 'application/json',
          text: JSON.stringify(owaspTop10, null, 2),
        },
      ],
    })
  );
}
